### ISSUE TITLE
UTF8 encoding problem

### ISSUE THREAD

**Issue by MilosStanic** [brianloveswords/node-jws#17]
Your library is used by node-jsonwebtoken, and when it signs the token using your library it seems that it breaks the payload if there is an UTF8 character in the payload. 
When I retrieve the token and decode it, and when I parse with JSON.parse() I get 'Unexpected token' error if the payload contained UTF8 chars. 
In my case it was char 'ć' .
Can you verify?

**Comment by frantello** [comment]
[Take a look](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding)

**Comment by MilosStanic** [comment]
thanks, I think I solved my problem. Not very happily, but solved it :)

**Comment by brianloveswords** [comment]
Hey @MilosStanic, I just published [v2.0.0] of `jws` which should fix your problem. I changed the default encoding from `binary` to `utf8` and added an option to override the default.

[v2.0.0]: https://github.com/brianloveswords/node-jws/blob/master/CHANGELOG.md#200---2015-01-30

**Comment by MilosStanic** [comment]
Hi @brianloveswords, thanks. I kinda solved my problem by escaping utf-8 chars before encoding them, and unescaping them after. But let's see how jws 2.0.0 works out when it gets adopted in the jsonwebtoken
