### ISSUE TITLE
test key for EC256 is of the wrong type?

### ISSUE THREAD

**Issue by diracdeltas** [brianloveswords/node-jws#19]
in https://github.com/brianloveswords/node-jws/blob/master/Makefile#L12:
```
@openssl ecparam -out test/ec256-private.pem -name secp256k1 -genkey
```

shouldn't this be prime256v1(NIST P-256) instead of secp256k1?

**Comment by dlg-yahoo** [comment]
Yes, the Koblitz curve would be completely wrong.
