### ISSUE TITLE
Fix for security flaw

### ISSUE THREAD

**Issue by odino** [brianloveswords/node-jws#21]
I saw [this](https://github.com/brianloveswords/node-jws/commit/585d0e1e97b6747c10cf5b7689ccc5618a89b299) was implemented for disallowing arbitrary algorithms to be verified, I guess to prevent the `none` one to always go through. Though this breaks the spec which says the server should not have prior knowledge of the algorithm.

Would you consider disabling `none` by default rather than changing the signature of `verify()`?

**Comment by arikalfus** [comment]
If you read [this] (https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) article describing the security flaw, changing the signature is actually a better way to mitigate the flaw. From the article: 

> The server should already know what algorithm it uses to sign tokens, and it's not safe to allow attackers to provide this value.

There's several paragraphs that explain why it's not safe to allow an alg header, so I'll let the article defend that.

**Comment by odino** [comment]
ok , up to you :) Just pointing out that the spec is kinda broken with these changes :)

I guess the draft will change in order to avoid allowing mixed families of algorithms to be used together, though I guess it'll take some time.

Cheers!

**Comment by omsmith** [comment]
@odino This doesn't necessarily require the server to have prior knowledge of the algorithm. For instance, at D2L, we decode the token to look at `kid` in the header, and fetch the appropriate key to verify it with. Assuming we were able to find such a key, we then restrict the set of algorithms to ones that key could possibly support.

**Comment by omsmith** [comment]
Closing, as not particularly actionable
