### ISSUE TITLE
JTI Support

### ISSUE THREAD

**Issue by tylerFowler** [brianloveswords/node-jws#26]
I'd like to see the JTI ([JWT ID](http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.4.1.7)) claim implemented so that I could, say, keep track of 'active' tokens out in the wild. And like the spec says it could be used to help prevent any replay attacks.

Are there any plans for this?

**Comment by brianloveswords** [comment]
Hi @tylerFowler! This library is an implementation of the [JWS spec](https://tools.ietf.org/html/rfc7515). JWT uses JWS, but JWS doesn't care about claims or anything in the body of the message. A JWT library based off this JWS library should have problem implementing the JTI claim.

**Comment by brianloveswords** [comment]
Closing this for now, if I'm misunderstanding something, feel free to re-open!

**Comment by tylerFowler** [comment]
Ah, I was actually a little confused about the distinction to be honest, I came here from the [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) package and figured this might be the place but I'll move it over to there.

Thanks!

**Comment by brianloveswords** [comment]
@tylerFowler looks like someone opened a PR for JTI stuff over there! https://github.com/auth0/node-jsonwebtoken/pull/102

**Comment by tylerFowler** [comment]
That's what I get for only looking at the issues! Well it looks like that does more or less what I was looking for.
