### ISSUE TITLE
Does JWS support verification with a PKCS#8 public key?

### ISSUE THREAD

**Issue by jedd-ahyoung** [brianloveswords/node-jws#33]
I know that JWS can support reading a PEM key using the PCKS#1 encoding - a public key looks like this:

    -----BEGIN RSA PUBLIC KEY-----
	MIIBCgKCAQEAwEYqf3HAL+h0CbcM6cnVfT6hDw0nNPkLYKld54qRYhJa+txnI8so
	bIhP4/1l3TnNZldFFOatRlZAxuNG8Dk4L/QQmDeIsOkYQ5oiytSCbUrJv44aOPjL
	G72XhVOaOLMT2vp/guOVAjTYOyF83asoOpPVtFeiBHhKudMrpPzeq3qwGMxfVVPy
	NlztFjnTlkAKMtkbkwcpzdTn4y/pDo47+LgkDckReoqTIK4Z1bp86Oa6eBOa7/6w
	hIXG3aCQiMQfJUBEBRA7mmV4g+jNWMhCBMEsOZj+KUErfilPv1FL4zP3E8kNCu+B
	GYCSuj0doIxreVHDifXd+5Lmhr6NDkhG5QIDAQAB
	-----END RSA PUBLIC KEY-----

Does it support the PCKS#8 encoding, which defines the key type within the payload itself? (Note that these are the same - this format includes the Object Identifier as part of the key and omits 'RSA').

	-----BEGIN PUBLIC KEY-----
	MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
	MIIBCgKCAQEAwEYqf3HAL+h0CbcM6cnVfT6hDw0nNPkLYKld54qRYhJa+txnI8so
	bIhP4/1l3TnNZldFFOatRlZAxuNG8Dk4L/QQmDeIsOkYQ5oiytSCbUrJv44aOPjL
	G72XhVOaOLMT2vp/guOVAjTYOyF83asoOpPVtFeiBHhKudMrpPzeq3qwGMxfVVPy
	NlztFjnTlkAKMtkbkwcpzdTn4y/pDo47+LgkDckReoqTIK4Z1bp86Oa6eBOa7/6w
	hIXG3aCQiMQfJUBEBRA7mmV4g+jNWMhCBMEsOZj+KUErfilPv1FL4zP3E8kNCu+B
	GYCSuj0doIxreVHDifXd+5Lmhr6NDkhG5QIDAQAB
	-----END PUBLIC KEY-----

**Comment by omsmith** [comment]
[node-jwa](https://github.com/brianloveswords/node-jwa) and thus node-jws simply use the node _crypto_ module, so whatever that supports https://iojs.org/api/crypto.html#crypto_crypto_createsign_algorithm
