### ISSUE TITLE
Support for PS256, PS384, and PS512

### ISSUE THREAD

**Issue by juergenzimmermann** [brianloveswords/node-jws#47]
It would be nice to have also support for the RSASSA-PSS algorithms as mentioned at https://tools.ietf.org/html/rfc7518#section-3.1

**Comment by chrisschaub** [comment]
Is PS256 supported?

**Comment by omsmith** [comment]
Available in [v3.2.0](https://github.com/brianloveswords/node-jws/releases/tag/v3.2.0).

https://github.com/brianloveswords/node-jws/commit/eb08645830a68a497a61511f7ccd799b172f8278

**Comment by csprl** [comment]
You probably also want to update https://github.com/brianloveswords/node-jws/blob/master/index.js#L5 :)

**Comment by omsmith** [comment]
Ha, good call
