### ISSUE TITLE
Binary payload is ruined by toString()

### ISSUE THREAD

**Issue by sandersaares** [brianloveswords/node-jws#50]
Despite ostensibly supporting a binary payload, the bytes of the payload are mangled by including a toString() call before encoding the payload (sign-stream.js:12).

``` JavaScript
var encodedPayload = base64url(toString(payload), encoding);
```

A Buffer is binary data - it is not supposed to be transformed into a string, as strings are not capable of containing arbitrary binary data. Right now, this defect mangles bytes outside some safe range (ASCII?).

Example code:

``` JavaScript
let jws = require("jws");
let payload = Buffer.from("TkJyotZe8NFpgdfnmgINqg==", "base64");
let secret = Buffer.from("8NRxgIkVxP8LyyXSL4b1dg==", "base64");

console.log(payload);

let token = jws.sign({
    "header": {
        "alg": "HS256"
    },
    "payload": payload,
    "secret": secret
});

console.log(token);
```

Expected result:

```
eyJhbGciOiJIUzI1NiJ9.TkJyotZe8NFpgdfnmgINqg.9XilaLN_sXqWFtlUCdAlGI85PCEbJZSIQpakyAle-vo
```

Actual result:

```
eyJhbGciOiJIUzI1NiJ9.TkJy_f1e_f1p_f39_QIN_Q.plu4DeDn9-SUCZvoneyACF3PXMc3F7wvb4P5gGKZagQ
```

**Comment by omsmith** [comment]
Care to test https://github.com/omsmith/node-jws/commit/f42ed46217e12e3cb546803fca967b50f91eeab1?

**Comment by sandersaares** [comment]
Looks good, thanks for fast action!

**Comment by omsmith** [comment]
Should be able to follow up with actual integration tonight/tomorrow.
