### ISSUE TITLE
Question about timing

### ISSUE THREAD

**Issue by brentschmaltz** [brianloveswords/node-jws#55]
Does this library have constant time failures?

Is the computation time the same if it's the first OR last byte of a signature that fails?

**Comment by omsmith** [comment]
Signature verification is done in [jwa](https://github.com/brianloveswords/node-jwa). HMAC verification is done [as reliably in constant time](https://github.com/brianloveswords/node-jwa/blob/master/index.js#L42) as can really be attempted in JS. Keypair verification is done by [Node.js crypto/OpenSSL](https://github.com/brianloveswords/node-jwa/blob/master/index.js#L67).
