### ISSUE TITLE
Update base64url dependency to 2.0.0 (smaller footprint)

### ISSUE THREAD

**Issue by yvele** [brianloveswords/node-jws#56]
I would be great to update [base64url](https://github.com/brianloveswords/base64url) dependency to [2.0.0](https://www.npmjs.com/package/base64url)

base64url 2.0.0 have a smaller footprint (no tests, config files, [cat image](https://github.com/brianloveswords/base64url/blob/master/test/test.jpg), etc. in the built package).

Thanks

**Comment by MarkHerhold** [comment]
@yvele $10 says @brianloveswords knows this as he is the owner of [base64url](https://github.com/brianloveswords/base64url)
