### ISSUE TITLE
Please ship a patch release

### ISSUE THREAD

**Issue by MarkHerhold** [brianloveswords/node-jws#59]
@omsmith Could you do a patch release in order to ship the changes from PR #58 ?

Thanks!

**Comment by MarkHerhold** [comment]
Ping @omsmith 🙏

**Comment by owenallenaz** [comment]
I'm seconding this. Node 7 now reports a DeprecationWarning due to the older version of base64url attached to this package.

```
(node:26202) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
    at Buffer (buffer.js:79:13)
    at base64url (/sv_local/node_modules/npm/googleapis/1/node_modules/base64url/index.js:41:21)
```

When I use the newer version of base64url I do not get the warning.
