### ISSUE TITLE
do we need tests for auth0's Tim McLean's jwt forgery claims

### ISSUE THREAD

**Issue by borromeotlhs** [brianloveswords/node-jws#67]
do we need to make tests for this?  I tried, but don't think I'm doing it right -OR- this library is already protected against the forged tokens.

**Comment by borromeotlhs** [comment]
example test file attached (last test for forged tokens).
[jws.test.js.txt](https://github.com/brianloveswords/node-jws/files/978041/jws.test.js.txt)

**Comment by omsmith** [comment]
Given the caller is required to specify the algorithm, the library itself it not susceptible, no.
