### ISSUE TITLE
build error while using jsonwebtokens in Angular6

### ISSUE THREAD

**Issue by thatham** [brianloveswords/node-jws#78]
ERROR in ./node_modules/jws/lib/verify-stream.js
Module not found: Error: Can't resolve 'stream' in 'E:\My Code\mycode\pwa\node_modules\jws\lib'
ERROR in ./node_modules/jws/lib/data-stream.js
Module not found: Error: Can't resolve 'stream' in 'E:\My Code\mycode\pwa\node_modules\jws\lib'
ERROR in ./node_modules/jws/lib/sign-stream.js
Module not found: Error: Can't resolve 'stream' in 'E:\My Code\mycode\pwa\node_modules\jws\lib'

**Comment by omsmith** [comment]
Ref: https://github.com/brianloveswords/node-jwa/issues/28
