### ISSUE TITLE
Update jwa to 1.1.6 to fix base64url vulnerability

### ISSUE THREAD

**Issue by lgodmer** [brianloveswords/node-jws#81]
Security vulnerability scanners like Snyk are still emitting errors about base64url@2.2.0 due to the dependency on jwa@1.1.5. 
Consider updating to jwa@1.1.6 which removes the base64url dependency.

**Comment by JSteunou** [comment]
Dependency is loose so you just have to reinstall or update yourself with npm. Use the command `npm audit` advises to use after running it.

**Comment by lgodmer** [comment]
Got it, thanks a lot for the response!
